version: '3.1'
services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
networks:
  default:
    external:
      name: localnet

